### ISSUE TITLE
#1. add splash screen

### ISSUE THREAD

**Issue by oscaryang-k** [oscaryang-k/react-native-paper-boilerplate#5]
add simple splash screen before authentication pages

**Comment by oscaryang-angelsoft** [comment]
![image](https://user-images.githubusercontent.com/117616805/209481607-329ed410-60f5-42f7-a941-573447c800af.png)

<Background>
  <Image source={require("./assets/logo.png")} style={style.logo} />
</Background>

const style = StyleSheet.create({
  logo: {
    width: "100%",
    resizeMode: "contain",
  },
});

**Comment by katochojiro** [comment]
```
<Background>
  <Image source={require("./assets/logo.png")} style={style.logo} />
</Background>
```
```

const style = StyleSheet.create({
  logo: {
    width: "100%",
    resizeMode: "contain",
  },
});

```

**Comment by oscaryang-angelsoft** [comment]
> add simple splash screen before authentication pages

```
<Background>
  <Image source={require("./assets/logo.png")} style={style.logo} />
</Background>
```
```

const style = StyleSheet.create({
  logo: {
    width: "100%",
    resizeMode: "contain",
  },
});

```

**Comment by chenkang-secret** [comment]
> add simple splash screen before authentication pages

sdfsdfsdf

**Comment by oscaryang-angelsoft** [comment]
> > add simple splash screen before authentication pages
> 
> sdfsdfsdf

asdasd
